NguyenHungCuong2011060110/ViewModels/CoursesViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using NguyenHungCuong2011060110.Models;

namespace NguyenHungCuong2011060110.ViewModels
{
    public class CoursesViewModel
    {
        public IEnumerable<Course> UpcommingCourses { get; set; }
        public bool ShowAction { get; set; }
    }
}

NguyenHungCuong2011060110/Controllers/CoursesController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using NguyenHungCuong2011060110.Models;
using NguyenHungCuong2011060110.ViewModels;

namespace NguyenHungCuong2011060110.Controllers
{
    
            
    public class CoursesController : Controller
    {
        private readonly ApplicationDbContext _dbContext;
        public CoursesController()
        {
            _dbContext = new ApplicationDbContext();
        }
        
        // GET: Courses
        [Authorize]
        public ActionResult Create()
        {
            var viewModel = new CourseViewModel
            {
                Categories = _dbContext.Categories.ToList()
            };
            return View(viewModel);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]

        public ActionResult Create(CourseViewModel viewModel)
        {
            if (!ModelState.IsValid)
            {
                viewModel.Categories = _dbContext.Categories.ToList();
                return View("Create", viewModel);
            }
            var course = new Course
            {
                LecturerId = User.Identity.GetUserId(),
                DateTime = viewModel.GetDateTime(),
                CategoryId = viewModel.Category,
                Place = viewModel.Place
            };
            _dbContext.Courses.Add(course);
            _dbContext.SaveChanges();
            return RedirectToAction("Index","Home");
        }
        [Authorize]
        public ActionResult Attending()
        {
            var userId =User.Identity.GetUserId();
            var courses =_dbContext.Attendances
                .Where(a=>a.AttendeeID == userId)
                .Select(a=>a.Course)
                .Include(l=>l.Lecturer)
                .Include(l=>l.Category)
                .ToList();
            var viewModel = new CoursesViewModel
            {
                UpcommingCourses = courses,
                ShowAction = User.Identity.IsAuthenticated,
            };
            return View(viewModel);
        }
    }
}

NguyenHungCuong2011060110/Views/Courses/Attending.cshtml
@model NguyenHungCuong2011060110.ViewModels.CoursesViewModel
@{
    ViewBag.Title = "Attending";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Attending</h2>

<ul class="course">
    @foreach (var course in Model.UpcommingCourses)
    {
        <li>
            @course.DateTime - @course.Lecturer.Name
        </li>
    }
</ul>

NguyenHungCuong2011060110/Views/Courses/Create.cshtml
@model NguyenHungCuong2011060110.ViewModels.CourseViewModel
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm("Create", "Courses"))
{
    @Html.AntiForgeryToken()
    <div class="form-group">
        @Html.LabelFor(m => m.Place)
        @Html.TextBoxFor(m => m.Place, new { @class = "form-control" })
        @Html.ValidationMessageFor(m=>m.Place)

    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Date)
        @Html.TextBoxFor(m => m.Date, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.Date)

    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Time)
        @Html.TextBoxFor(m => m.Time, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.Time)

    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Category)
        @Html.DropDownListFor(m => m.Category, new SelectList(Model.Categories, "Id", "Name"), "", new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.Category)

    </div>
    <button style="margin-top:5px;" type="submit" value="Save" class="btn btn-primary">Save</button>

    <div class="form-group"></div>
    <div class="form-group"></div>
    <div class="form-group"></div>
    <div class="form-group"></div>
}
@section scripts{
    @Scripts.Render("~/bundles/jqueryval");
    }